### ISSUE TITLE
[Critique] Mise a jour (Refresh Datas ?)

### ISSUE THREAD

**Issue by cedric222** [bobox59/arduidom#3]
Pour le moment, les changements d'états ne sont envoyé a Jeedom que si il y a un changement d'état.

Dans le cas, par exemple ou le touche à la configuration d'une commande dans Jeedom, elle est passé à 0 par jeedom... et tant qu'elle reste a 1 sur l'arduino, Jeedom n'est pas mis a jour.

Il semble y avoir une commande RF "refresh data" dans le arduidom.py, qui met a jour la totalité des pin
Il faudrait, après chaque changement de config jeedomm, lancer cette commande pour tout rafraichir.

(On pourrait aussi la lancer régulièrement, en cas de désynchro entre l'arduino et jeedom)

**Comment by bobox59** [comment]
corrigé ici https://github.com/bobox59/arduidom/commit/a9ab43f2581c09a21f620fc9513130e7137d38d7

**Comment by cedric222** [comment]
mais supprimer a nouveau ici !  e97863dba955cd8d2b370520a8ad8373ad797acc !
normal ?
